apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      containers:
        - name: test-server
          image: angularhclacr.azurecr.io/newjava-app:latest
          imagePullPolicy: "Always"
          ports:
            - name: http-port
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  selector:
    app: test-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: LoadBalancer
